# Generated by Django 5.2.4 on 2025-07-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='Size')),
                ('color', models.CharField(choices=[('white', 'Trắng'), ('black', 'Đen'), ('gray', 'Xám'), ('beige', 'Be'), ('pink', 'Hồng'), ('blue', 'Xanh dương'), ('navy', 'Navy'), ('brown', 'Nâu'), ('red', 'Đỏ'), ('yellow', 'Vàng'), ('green', 'Xanh lá'), ('purple', 'Tím')], max_length=20, verbose_name='Màu sắc')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('sku', models.CharField(help_text='Mã sản phẩm theo size và màu', max_length=50, unique=True, verbose_name='SKU')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='customer_web.product')),
            ],
            options={
                'verbose_name': 'Tồn kho sản phẩm',
                'verbose_name_plural': 'Tồn kho sản phẩm',
                'ordering': ['product', 'color', 'size'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
