# Generated by Django 5.2.4 on 2025-07-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_web', '0002_productinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Số tiền hoàn'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt hoàn trả'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn trả hoàn tất'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='Lý do hoàn trả'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày yêu cầu hoàn trả'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy'), ('return_requested', 'Yêu cầu hoàn trả'), ('return_approved', 'Đã duyệt hoàn trả'), ('returned', 'Đã hoàn trả'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20),
        ),
    ]
