# Generated by Django 5.2.4 on 2025-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_web', '0003_order_refund_amount_order_refund_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_trend',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm Hot Trend'),
        ),
    ]
