# Generated by Django 5.2.4 on 2025-07-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_web', '0004_add_hot_trend_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='customer_web.category', verbose_name='Danh mục'),
        ),
    ]
