# Generated by Django 5.2.4 on 2025-08-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_web', '0005_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('transfer', 'Chuyển khoản ngân hàng')], default='cod', max_length=20),
        ),
    ]
