# Generated by Django 5.2.4 on 2025-07-21 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CotoKid Admin', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='dashboard/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt Dashboard',
                'verbose_name_plural': 'Cài đặt Dashboard',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Tóm tắt')),
                ('featured_image', models.ImageField(upload_to='news/', verbose_name='Ảnh đại diện')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã xuất bản')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-created_at'],
            },
        ),
    ]
